### ISSUE TITLE
KeyError: 'ESSID'

### ISSUE THREAD

**Issue by llazzaro** [llazzaro/wifi_tools#2]
```
Traceback (most recent call last):
  File "/home/pi/wifi_tools/wifi_tools/sniff/aircrack.py", line 46, in tick
    tree_data = self.process_tree()
  File "/home/pi/wifi_tools/wifi_tools/sniff/aircrack.py", line 91, in process_tree
    data['ssid'] = data['ESSID']
KeyError: 'ESSID'
```

**Comment by llazzaro** [comment]
pyrcrack was causing the bug.
Added exception catch
